version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: echo "TODO"
workflows:
    build-and-deploy:
      jobs:
        - build-and-test:
            filters:
              tags:
                only: /^v.*/
        - deploy :
            requires:
                - build-and-test
            filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/