version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - run: ssh-keyscan 104.197.233.50 >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "SHA256:hkuJKFIgygmcIERdItQL90/H2Bc2rmGe1PeaUpH7cvU"
      - node/with-cache:
          steps:
            - run: npm run build
            - run: cd build
            - run: scp -r * amholt05@104.197.233.50:/opt/tomcat/webapps/onuw-server
workflows:
    build-and-deploy:
      jobs:
        - build-and-test:
            filters:
              tags:
                only: /^v.*/
        - deploy :
            requires:
                - build-and-test
            filters:
              tags:
                only: /^v.*/
              # branches:
              #   ignore: /.*/