version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:hkuJKFIgygmcIERdItQL90/H2Bc2rmGe1PeaUpH7cvU"
      - node/with-cache:
          steps:
            - run: echo "TODO"
            - run: ls 
            - run: ssh amholt05@104.197.233.50
            - run: scp -r amholt05@104.197.233.50 build
workflows:
    build-and-deploy:
      jobs:
        - build-and-test:
            filters:
              tags:
                only: /^v.*/
        - deploy :
            requires:
                - build-and-test
            filters:
              tags:
                only: /^v.*/
              # branches:
              #   ignore: /.*/